# top level stuff you probably don't need to touch
highlighter: pygments
# markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
#paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://vijaykoju.github.io/
basurl: /
title: Vijay Koju
author: Vijay Koju
description: Personal blog and resume
avatar: vijay.jpg
email: vijaykoju@gmail.com
github: vijaykoju
#twitter: biomadeira
#google_analytics: UA-47728743-1
